apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      containers:
        - name: logservice
          image: gtzfw/distributed_xray:logservice-latest
          env:
            - name: Registry_IP
              value: "regservice"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: logservice
spec:
  selector:
    app: logservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP