apiVersion: apps/v1
kind: Deployment
metadata:
  name: regservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regservice
  template:
    metadata:
      labels:
        app: regservice
    spec:
      containers:
        - name: regservice
          image: gtzfw/distributed_xray:regservice-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: regservice
spec:
  selector:
    app: regservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP