apiVersion: v1
kind: Secret
metadata:
  name: webservice-secret
type: Opaque
data:
  DB: cm9vdDpwYXNzd29yZEB0Y3AobXlzcWw6MzMwNikv
  REALITY_PUBKEY: cHVzMkRMX1hhaUNCSzA1ZGRJeW5WdGtZYjc1RWpCbTB2eUNvWnNVaTJ5dw==
  REALITY_PRIKEY: bU5vR3psTGJJVmRLTTBaSlk0c1ZaOElPbkZod2hkcGNJWVdCRFFfeFFpdw==
