apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: gtzfw/distributed_xray:webservice-latest
          imagePullPolicy: Always
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: webservice-secret
                  key: DB
            - name: Registry_IP
              value: "regservice"
            - name: REALITY_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: webservice-secret
                  key: REALITY_PUBKEY
            - name: REALITY_PRIKEY
              valueFrom:
                secretKeyRef:
                  name: webservice-secret
                  key: REALITY_PRIKEY
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
